import { RETAINED_DATA_INVENTORY } from './data-inventory';

// Reviewed allowlists: adding a Prisma field does not silently expose it.
export const EXPORT_PROJECTIONS = {
  AccountErasureJob: [
    'id',
    'state',
    'revocationStatus',
    'requestedAt',
    'localDeletedAt',
    'completedAt',
    'receiptExpiresAt',
    'retainedUntil',
  ],
  Todo: ['ownerId', 'id', 'text', 'done', 'doneAt', 'createdAt'],
  CalendarEvent: ['ownerId', 'id', 'title', 'when', 'createdAt'],
  Note: ['ownerId', 'id', 'title', 'text', 'createdAt'],
  ShoppingItem: ['ownerId', 'id', 'text', 'bought', 'boughtAt', 'createdAt'],
  PersonalFact: ['ownerId', 'id', 'text', 'origin', 'createdAt', 'updatedAt'],
  RoutineSetting: ['ownerId', 'routineKey', 'enabled', 'updatedAt'],
  RoutineRun: [
    'ownerId',
    'id',
    'routineKey',
    'requestId',
    'state',
    'steps',
    'result',
    'createdAt',
    'updatedAt',
  ],
  PendingAction: [
    'id',
    'sessionId',
    'name',
    'argsJson',
    'createdAt',
    'expiresAt',
  ],
  JarvisLog: [
    'id',
    'sessionId',
    'userText',
    'modelRaw',
    'toolName',
    'toolArgs',
    'result',
    'simulation',
    'createdAt',
  ],
  GoogleOAuthToken: null,
  JarvisHumanProfile: [
    'sessionId',
    'speechMode',
    'verbosity',
    'preferredName',
    'turnCount',
    'createdAt',
    'updatedAt',
  ],
  JarvisMemoryFact: [
    'id',
    'sessionId',
    'layer',
    'key',
    'label',
    'value',
    'confidence',
    'source',
    'lastSeenAt',
    'createdAt',
    'updatedAt',
  ],
  JarvisSessionSummary: [
    'sessionId',
    'summary',
    'highlightsJson',
    'createdAt',
    'updatedAt',
  ],
  JarvisMission: [
    'id',
    'sessionId',
    'objective',
    'objectiveKey',
    'horizon',
    'status',
    'summary',
    'nextStep',
    'planText',
    'keySignalsJson',
    'createdAt',
    'updatedAt',
  ],
  JarvisActionEvent: [
    'id',
    'sessionId',
    'pendingActionId',
    'source',
    'toolName',
    'summary',
    'argsJson',
    'planner',
    'confidence',
    'risk',
    'status',
    'resultPreview',
    'errorMessage',
    'completedAt',
    'createdAt',
    'updatedAt',
  ],
  JarvisWorkflowMemory: [
    'id',
    'sessionId',
    'triggerToolName',
    'triggerSummary',
    'followUpToolName',
    'followUpPrompt',
    'followUpPromptKey',
    'usageCount',
    'lastUsedAt',
    'createdAt',
    'updatedAt',
  ],
  JarvisGoal: [
    'id',
    'sessionId',
    'title',
    'description',
    'priority',
    'targetDate',
    'status',
    'parentGoalId',
    'createdAt',
    'updatedAt',
  ],
  JarvisTaskDependency: [
    'id',
    'sessionId',
    'sourceTaskId',
    'targetTaskId',
    'dependencyType',
    'estimatedDays',
    'createdAt',
    'updatedAt',
  ],
  JarvisResourceAllocation: [
    'id',
    'sessionId',
    'resourceType',
    'resourceName',
    'allocatedHours',
    'usedHours',
    'allocationDate',
    'expiryDate',
    'createdAt',
    'updatedAt',
  ],
  JarvisPredictiveMetric: [
    'id',
    'sessionId',
    'metricType',
    'historicalData',
    'forecast',
    'accuracy',
    'forecastedAt',
    'createdAt',
    'updatedAt',
  ],
  JarvisSchedulingSuggestion: [
    'id',
    'sessionId',
    'taskId',
    'suggestedTime',
    'rationale',
    'priority',
    'applied',
    'createdAt',
    'updatedAt',
  ],
  JarvisContextualHelp: [
    'id',
    'sessionId',
    'context',
    'contentType',
    'content',
    'relevanceScore',
    'viewedCount',
    'helpful',
    'createdAt',
    'updatedAt',
  ],
  JarvisKnowledgeEntry: [
    'id',
    'sessionId',
    'title',
    'content',
    'tags',
    'category',
    'useCount',
    'createdAt',
    'updatedAt',
  ],
  JarvisTimeInsight: [
    'id',
    'sessionId',
    'metricName',
    'value',
    'unit',
    'period',
    'periodStart',
    'periodEnd',
    'createdAt',
    'updatedAt',
  ],
  JarvisDelegation: [
    'id',
    'sessionId',
    'taskDescription',
    'delegateTo',
    'reason',
    'priority',
    'status',
    'dueDate',
    'resolvedAt',
    'resolutionNote',
    'createdAt',
    'updatedAt',
  ],
  Reminder: [
    'id',
    'sessionId',
    'text',
    'triggerAt',
    'done',
    'doneAt',
    'snoozedUntil',
    'recurring',
    'rrule',
    'createdAt',
    'updatedAt',
  ],
  Habit: [
    'id',
    'sessionId',
    'name',
    'emoji',
    'frequency',
    'archived',
    'createdAt',
    'updatedAt',
  ],
  HabitLog: ['id', 'habitId', 'date', 'note', 'createdAt'],
  Contact: [
    'id',
    'sessionId',
    'name',
    'email',
    'phone',
    'company',
    'role',
    'notes',
    'tags',
    'lastInteractionAt',
    'createdAt',
    'updatedAt',
  ],
  Expense: [
    'id',
    'sessionId',
    'amount',
    'currency',
    'category',
    'description',
    'date',
    'createdAt',
  ],
  Budget: [
    'id',
    'sessionId',
    'category',
    'limit',
    'period',
    'currency',
    'createdAt',
    'updatedAt',
  ],
  InboxZeroSession: [
    'sessionId',
    'status',
    'step',
    'query',
    'startedAt',
    'scannedAt',
    'updatedAt',
  ],
  InboxZeroItem: [
    'id',
    'sessionId',
    'googleAccountId',
    'googleAccountSubject',
    'messageId',
    'threadId',
    'subject',
    'from',
    'to',
    'date',
    'snippet',
    'labelsJson',
    'gmailCategory',
    'unread',
    'category',
    'priority',
    'reason',
    'suggestedJson',
    'status',
    'lastActionAt',
    'createdAt',
    'updatedAt',
  ],
  InboxZeroAction: [
    'id',
    'sessionId',
    'messageId',
    'actionType',
    'payloadJson',
    'status',
    'errorMessage',
    'createdAt',
  ],
  User: [
    'id',
    'name',
    'email',
    'emailVerified',
    'image',
    'disabled',
    'displayTimezone',
    'theme',
    'onboardingCompleted',
    'createdAt',
    'updatedAt',
  ],
  Conversation: ['id', 'clientKey', 'ownerId', 'createdAt'],
  InboxReplyOperation: [
    'id',
    'ownerId',
    'conversationId',
    'requestId',
    'digest',
    'intent',
    'sendState',
    'providerMessageId',
    'providerThreadId',
    'labelsComplete',
    'localComplete',
    'createdAt',
    'updatedAt',
  ],
  Command: [
    'id',
    'ownerId',
    'conversationId',
    'requestId',
    'toolName',
    'toolVersion',
    'source',
    'arguments',
    'targets',
    'digest',
    'state',
    'revision',
    'approvedDigest',
    'approvedAt',
    'outcomeCode',
    'response',
    'expiresAt',
    'createdAt',
    'updatedAt',
  ],
  ConversationTurn: [
    'id',
    'ownerId',
    'conversationId',
    'kind',
    'inputText',
    'state',
    'response',
    'commandId',
    'createdAt',
    'updatedAt',
  ],
  CommandTransition: [
    'commandId',
    'revision',
    'fromState',
    'toState',
    'approvedDigest',
    'outcomeCode',
    'createdAt',
  ],
  IntegrationAccount: [
    'id',
    'ownerId',
    'provider',
    'providerSubject',
    'createdAt',
  ],
  GoogleOAuthState: null,
  LegacyOwnershipBatch: null,
  LegacyOwnershipRecord: [
    'batchId',
    'tableName',
    'recordId',
    'original',
    'assignedOwnerId',
  ],
  Session: [
    'id',
    'expiresAt',
    'createdAt',
    'updatedAt',
    'ipAddress',
    'userAgent',
    'userId',
  ],
  Account: [
    'id',
    'accountId',
    'providerId',
    'userId',
    'accessTokenExpiresAt',
    'refreshTokenExpiresAt',
    'scope',
    'createdAt',
    'updatedAt',
  ],
  Verification: null,
  BetaInvite: ['email', 'createdAt', 'expiresAt', 'revokedAt'],
  CommandCompensation: [
    'commandId',
    'label',
    'changes',
    'consumedAt',
    'createdAt',
  ],
  InboxReplyDraft: [
    'ownerId',
    'conversationId',
    'messageId',
    'text',
    'version',
    'updatedAt',
  ],
} as const satisfies Record<
  keyof typeof RETAINED_DATA_INVENTORY,
  readonly string[] | null
>;
